"""
Error Handling Infrastructure.

Provides exceptions, retry logic, and circuit breaker.
"""

from .exceptions import (
    MidasException,
    DatabaseError,
    RecordNotFoundError,
    DuplicateRecordError,
    DatabaseConnectionError,
    ValidationError,
    InvalidAmountError,
    InvalidCurrencyError,
    InvalidDateError,
    InsufficientBalanceError,
    ExternalAPIError,
    BlockchainAPIError,
    AIServiceError,
    RateLimitExceededError,
    BusinessLogicError,
    WalletNotFoundError,
    CategoryNotFoundError,
    TransactionNotFoundError,
    DuplicateTransactionError,
    ImportError,
    CSVParseError,
    UnsupportedFormatError,
    SecurityError,
    UnauthorizedError,
    EncryptionError,
    DecryptionError,
    get_user_friendly_message,
)

from .retry import (
    RetryConfig,
    DEFAULT_RETRY_CONFIG,
    AGGRESSIVE_RETRY_CONFIG,
    CONSERVATIVE_RETRY_CONFIG,
    retry_async,
    with_retry,
    CircuitBreaker,
    CircuitBreakerOpenError,
    with_circuit_breaker,
)

__all__ = [
    # Exceptions
    "MidasException",
    "DatabaseError",
    "RecordNotFoundError",
    "DuplicateRecordError",
    "DatabaseConnectionError",
    "ValidationError",
    "InvalidAmountError",
    "InvalidCurrencyError",
    "InvalidDateError",
    "InsufficientBalanceError",
    "ExternalAPIError",
    "BlockchainAPIError",
    "AIServiceError",
    "RateLimitExceededError",
    "BusinessLogicError",
    "WalletNotFoundError",
    "CategoryNotFoundError",
    "TransactionNotFoundError",
    "DuplicateTransactionError",
    "ImportError",
    "CSVParseError",
    "UnsupportedFormatError",
    "SecurityError",
    "UnauthorizedError",
    "EncryptionError",
    "DecryptionError",
    "get_user_friendly_message",
    # Retry
    "RetryConfig",
    "DEFAULT_RETRY_CONFIG",
    "AGGRESSIVE_RETRY_CONFIG",
    "CONSERVATIVE_RETRY_CONFIG",
    "retry_async",
    "with_retry",
    "CircuitBreaker",
    "CircuitBreakerOpenError",
    "with_circuit_breaker",
]
